#!/usr/bin/env python3
"""Export a compact context pack for the next Codex run."""

from __future__ import annotations

from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "context" / "current_context.md"

CONTEXT_FILES = [
    "README.md",
    "AGENTS.md",
    "config/learner_profile.yaml",
    "state/progress.yaml",
    "state/next_actions.md",
]

MANUAL_MARKER = "## Manual Notes"


def read_text(path: Path) -> str:
    if not path.exists():
        return f"[missing: {path.relative_to(ROOT)}]"
    return path.read_text(encoding="utf-8").strip()


def extract_manual_notes() -> str:
    if not OUTPUT.exists():
        return "- No manual notes yet."
    text = OUTPUT.read_text(encoding="utf-8")
    if MANUAL_MARKER not in text:
        return "- No manual notes yet."
    return text.split(MANUAL_MARKER, 1)[1].strip() or "- No manual notes yet."


def main() -> int:
    manual_notes = extract_manual_notes()
    parts = [
        "# Current Context",
        "",
        f"Generated on: {date.today().isoformat()}",
        "",
        "This file is a compact handoff pack for Codex. It is generated by `scripts/export_context_pack.py`.",
        "",
    ]

    for rel_path in CONTEXT_FILES:
        text = read_text(ROOT / rel_path)
        parts.extend(
            [
                f"## {rel_path}",
                "",
                "```text",
                text,
                "```",
                "",
            ]
        )

    parts.extend([MANUAL_MARKER, "", manual_notes, ""])
    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(CONTEXT_FILES)} source files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

